tinder:
  crawler:
    #Кол-во заборов новых рекомендаций за срабатывание шедулера
    loops: 1
    #Переодичность забора новых рекомендаций
    cron: "0 0/50 * * * *"
    #Переодичность автоматической синхронизации вердиктов
    bvsync: "0 */5 * * * *"
    #Переодичность автолайков(можно отключить - просто проставив "-" вместо cron expression)
    autolike: "0 0 11,23 * * *"
    #Автоматически синхронизировать автолайки
    auto-superlike-sync: true
    #    autolike: "0 */5 * * * *" 5 мин для отладки

    #В момент забора печатать в консоль id с хорошим рейтингом(больше этого порога)
    rating-print-treshold: 30
    #Настройки для авторизации в фейсбук
    fb:
      token-url: https://www.facebook.com/v2.6/dialog/oauth?redirect_uri=fb464891386855067%3A%2F%2Fauthorize%2F&scope=user_birthday%2Cuser_photos%2Cuser_education_history%2Cemail%2Cuser_relationship_details%2Cuser_friends%2Cuser_work_history%2Cuser_likes&response_type=token%2Csigned_request&client_id=464891386855067
      login-url: https://www.facebook.com/login.php
  img-cache:
    #Включен ли кеш изображений
    enabled: false
    #В случае если включен, нужно указать директорию куда складировать файлы
    dir: /media/mark/DATAPART1/img-cache
spring:
  profiles:
    include: facebook
  thymeleaf:
    cache: false
  datasource:
    #TODO: use tcrawler user
    url: jdbc:postgresql://localhost/tcrawler?user=postgres&password=postgres
    hikari:
      maximum-pool-size: 4
    driver-class-name: org.postgresql.Driver