tinder:
  crawler:
    #Кол-во заборов новых рекомендаций за срабатывание шедулера
    loops: 1
    #Переодичность забора новых рекомендаций
    cron: "0 0/50 * * * *"
    #В момент забора печатать в консоль id с хорошим рейтингом(больше этого порога)
    rating-print-treshold: 30
    #Профиль хрома
    chrome-profile-dir: /home/mark/.config/google-chrome/selenium
    facebook-token-url: https://www.facebook.com/v2.6/dialog/oauth?redirect_uri=fb464891386855067%3A%2F%2Fauthorize%2F&scope=user_birthday%2Cuser_photos%2Cuser_education_history%2Cemail%2Cuser_relationship_details%2Cuser_friends%2Cuser_work_history%2Cuser_likes&response_type=token%2Csigned_request&client_id=464891386855067
  img-cache:
    enabled: false
    dir: /media/mark/DATAPART1/img-cache
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:postgresql://localhost/tcrawler?user=postgres&password=postgres
    hikari:
      maximum-pool-size: 4
    driver-class-name: org.postgresql.Driver