tinder:
  crawler:
    loops: 4
    rating-print-treshold: 30
server:
  tomcat:
    uri-encoding:
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:postgresql://localhost/tcrawler?user=postgres&password=postgres
    hikari:
      maximum-pool-size: 4
    driver-class-name: org.postgresql.Driver